name: Continuous Integration
on:
  push:
    branches:
      - main
      - feature/*

env:
  IS_RELEASE: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
  IS_RC: ${{ github.ref == 'refs/heads/rc' }}
  IS_BETA: ${{ github.ref == 'refs/heads/dev' }}
  HUSKY: 0

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    # strategy:
    #   matrix:
    #     node-version: [20]
    #     npm-version: [9]
    #     yarn-version: ['1.22.x']
    #     pnpm-version: [8]
    steps:
      - name: Checkout [Default Branch]
        uses: actions/checkout@v4
        #if: ${{ github.event_name != 'pull_request' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Install PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - name: Git Version
        id: test-action
        uses: codedesignplus/semver-git-version@v0.1.4
        with:
          folder: ${{github.workspace}}
          release-branch: 'main'
          release-candidate-branch: 'rc'
          beta-branch: 'dev'
          major-identifier: 'breaking'
          minor-identifier: 'feat'
          prefix: 'v'
          previous-version: true
          new-version: true

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - run: |
          pnpm run affected
          pnpm run affected:submodule
          pnpm run format:check
          pnpm run affected:lint --target lint
          pnpm run affected:test --target test
          pnpm run affected:build --target build 
          pnpm run publish --npm-token=${{ secrets.NPM_TOKEN }} and --npm-gh-token=${{ secrets.GITHUB_TOKEN }}

      - name: Push tag
        id: push_tag
        # if: env.IS_RELEASE == 'true' || env.IS_RC == 'true' || env.IS_BETA == 'true'
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ steps.test-action.outputs.new-version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Changelog
        # if: env.IS_RELEASE == 'true' || env.IS_RC == 'true'
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: '${{ github.workspace }}/.github/settings/configuration.json'
          fromTag: ${{ steps.test-action.outputs.previous-version-prefix }}
          toTag: ${{ steps.test-action.outputs.new-version-prefix }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        # if: env.IS_RELEASE == 'true' || env.IS_RC == 'true'
        uses: mikepenz/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.test-action.outputs.new-version-prefix }}
          name: 'codedesignplus/nx@${{ steps.test-action.outputs.new-version-prefix }}'
          body: ${{ steps.build_changelog.outputs.changelog }}
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'dev') }}
